### ISSUE TITLE
Sockets

### ISSUE THREAD

**Issue by emilyb7** [CYPIAPT-LNDSE/goals-app#146]
- [x] link database to server #148
- [x] set up web sockets on client #149
- [x] set up web sockets on server #150
- [x] write reducers and tests #151
- [x] socket manager (client) #152
- [x] generating IDs for new goal #153
- [x] socket manager (server)

**Comment by shiryz** [comment]
@emilyb7 , happy to close this one?

**Comment by emilyb7** [comment]
yep : )
